version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "📌"
    labels:
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "📌"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "wednesday"
    commit-message:
      prefix: "👷"
    labels:
      - "dependencies"
